### PR TITLE
add profile photo other fixes

### PR DESCRIPTION
**Pull request by delebash**
added profile photo
edit for photos uploads 
spatie media set to single file collection
added search to blog page
code cleanup

### CODE REVIEW

**Comment by delebash** [comment]
@irabbi360 regarding the profile photo, I am not sure of the best way to update the admin nav bar when you upload or change your profile photo.  For now, once you upload a photo you can refresh the page or logout login.  I know you can reload a component in vue but I thought since you are better at programming you might know of an easy way.  TY. Cheers!

**Comment by delebash** [comment]
I did not notice you made some changes after the initial merge.  So this new commit does not have your code changes, also I did make some changes on the photos instead of returning two image urls one for resize and original I do the check on the controller and just return one.

**Comment by delebash** [comment]
The only other thing I think might be good would to make the Blog card size smaller.  I will wait until you merge any of my new commits and then I will merge my repo for a fresh start.  TY again for the help and this project.

**Comment by irabbi360** [comment]
Please fix the conflict.

**Comment by irabbi360** [comment]
Where & how can we view the uploaded profile images?

**Comment by delebash** [comment]
When you upload a profile photo you will see it next to your name.  Is this what you are asking?

**Pull request closed without merging**
